### ISSUE TITLE
User Story : Gestion partie

### ISSUE THREAD

**Issue by Gauthier-F** [riku59250/MeepleTown#2]

**Comment by Gauthier-F** [comment]
Thème | Gestion des parties

Titre | Session de jeu

Description | En tant qu'utilisateur je peux créer 
Détails | -via email / mot de passe , via compte gmail, via facebook
Test acceptation |

**Comment by Gauthier-F** [comment]
Thème | Gestion des parties

Titre | Ajout de participant à une session de jeu

Description | En tant qu'utilisateur je peux m'ajouter à une session de jeu

Détails | via bouton d'action qui l'ajoute à la liste des participants à une session de jeu

Test acceptation |  Que l'utilisateur soit bien ajouté à l'évènement et qu'il ne puisse pas s'ajouter à plusieurs sessions de jeu qui ont lieu en même temps.


Valeur ajouté |

Charge |

Complexité |

Risque |

**Comment by Gauthier-F** [comment]
Thème | Gestion des parties

Titre | Suppression du participant à une session de jeu

Description | En tant qu'utilisateur je peux m'enlever à une session de jeu

Détails | via bouton d'action qui le supprime de la liste des participants à une session de jeu

Test acceptation |  Que l'utilisateur soit bien retiré de l'évènement et que sa place soit de nouveau disponible pour d'autres utilisateurs


Valeur ajouté |

Charge |

Complexité |

Risque |

**Comment by Vanessa59** [comment]
**Thème :** Gestion des parties. 
**Titre :** Consultation des parties.
**Description :** En tant qu'utilisateur, je souhaite consulter la liste des parties disponibles.
**Détails :** 
- Ne voir que les parties auxquelles on peut accéder.

**Tests d'acceptation :** 
- Je peux voir les parties publiques.
- Je ne peux pas voir les parties privées.

**Comment by Vanessa59** [comment]
**Thème :** Gestion des parties. 
**Titre :** Consultation des parties.
**Description :** En tant qu'utilisateur, je souhaite filtrer la liste des parties disponibles par lieu.
**Détails :** 
- Par défaut, le tri se fait par date la plus récente en premier.

**Tests d'acceptation :** 
_______________________________________________
**Thème :** Gestion des parties. 
**Titre :** Consultation des parties.
**Description :** En tant qu'utilisateur, je souhaite filtrer la liste des parties disponibles par jeu.
**Détails :** 
- Par défaut, le tri se fait par date la plus récente en premier.

**Tests d'acceptation :** 
_______________________________________________
**Thème :** Gestion des parties. 
**Titre :** Consultation des parties.
**Description :** En tant qu'utilisateur, je souhaite filtrer la liste des parties disponibles par date.
**Détails :** 
- On accède à un calendrier sur lequel on sélectionne la date souhaitée.
- Par défaut, l'affichage se fait par ordre alphabétique des villes. 

**Tests d'acceptation :**

**Comment by Vanessa59** [comment]
**Thème :** Gestion des parties. 
**Titre :** Consultation d'une partie.
**Description :** En tant qu'utilisateur, je souhaite consulter la fiche d'une partie afin de connaître ses détails.
**Détails :** 


**Tests d'acceptation :**

**Comment by Vanessa59** [comment]
**Thème :** Gestion des parties. 
**Titre :** Modification d'une partie.
**Description :** En tant qu'utilisateur, je souhaite modifie une partie que j'ai créée afin de corriger les informations données.
**Détails :** 
- Toutes les zones sont modifiables.

**Tests d'acceptation :**
